#%RAML 1.0 DataType
properties:
  ConvenienceFeeProfileName:
    required: true
    type: string
    description: Unique Name of Convenience Fee Profile
  AchFixed:
    required: true
    type: string
    description: Fixed Amount in Dollars that has to be charged in ACH transaction as Convenience Fee
  AchVariable:
    required: true
    type: string
    description: Variable Amount in Dollars that has to be charged in ACH transaction as Convenience Fee
  AchMin:
    required: true
    type: string
    description: Maximum Amount in Dollars that has to be charged in ACH transaction as Convenience Fee
  AchMax:
    required: true
    type: string
    description: Maximum Amount in Dollars that has to be charged in ACH transaction as Convenience Fee
  AuthFixed:
    required: true
    type: string
    description: Fixed Amount in Dollars that has to be charged in Authorization transaction as Convenience Fee
  AuthVariable:
    required: true
    type: string
    description: Variable Amount in Dollars that has to be charged in Authorization transaction as Convenience Fee
  AuthMin:
    required: true
    type: string
    description: Minimum Amount in Dollars that has to be charged in Authorization transaction as Convenience Fee
  AuthMax:
    required: true
    type: string
    description:
  SaleFixed:
    required: true
    type: string
    description:
  SaleVariable:
    required: true
    type: string
    description:
  SaleMin:
    required: true
    type: string
    description:
  SaleMax:
    required: true
    type: string
    description:












