#%RAML 1.0 Trait
responses:
  400:
    description: Convenience Fee Profile Exists
  403:
    description: User not authorized to perform this action.
  404:
    description: User Token Details Missing
